services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - spark-network

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_EXECUTOR_MEMORY=2G
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - ./notebooks:/home/jovyan/work
    deploy:
      replicas: 4

  jupyter:
    build:
      context: .
      dockerfile: DockerfileNotebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge